# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

    #esi: true
    #fragments: true
    php_errors:
        log: true
    http_client:
        scoped_clients:
            discord.client:
                base_uri: 'https://discord.com/api/'
                headers:
                    Authorization: 'Bot %env(DISCORD_BOT)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
