version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    image: registry.silvain.eu:5000/silvain.eu/monsieurpatatephp:latest
    volumes:
      - .:/var/www
    working_dir: /var/www
    links:
      - redis
      - mailcatcher
      - database

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql # persist data even

  #  php_messenger:
  #    build:
  #      context: tools/docker/php/8.0
  #    command: bash -c "pwd && php bin/console messenger:consume async -vv"
  #    volumes:
  #      - ./var/www/node_modules
  #      - .:/var/www:cached
  #      - vendor:/var/www/vendor
  #      - var:/var/www/var/cache
  #    working_dir: /var/www
  #    links:
  #      - redis
  #      - mailcatcher
  #      - database

  yarn:
    image: node
    working_dir: /var/www
    tty: true
    volumes:
      - .:/var/www:delegated
    command: /bin/sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
      - 500:5000

  redis:
    image: redis:5-alpine

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1081:1080

volumes:
  var:
  vendor:
  node_modules:
  db-data:
    driver: local