controllers:
    resource: ../../src/Http/Main/Controller
    type: annotation

security_controllers:
    resource: ../../src/Http/Security/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
